# Generated by Django 3.2.13 on 2022-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
